Repository AlexanderSenchenko/Space-Invaders, pull requests merged in 2019-11, with the labels that each got.

#4 Added check ncurses, gcc and make
  .gitignore
  Makefile
  compilation.sh
  lol/lol.c
Labels: enhancement

#5 Graphics
  Makefile
  include/graphics/menu.h
  src/client.c
  src/graphics/menu.c
  src/main.c
Labels: Merge

#6 Graphics
  include/graphics/menu.h
  src/graphics/menu.c
Labels: Merge, Review

#7 Handling terminal resize signal
  include/graphics/menu.h
  src/graphics/menu.c
Labels: Fix, Merge

#8 simple funcs
  include/logic/bullet.h
  include/logic/enemy.h
  include/logic/game.h
  include/logic/models.h
  include/logic/user.h
  src/logic/bullet.c
  src/logic/enemy.c
  src/logic/models.c
  src/logic/user.c
Labels: Review

#9 Init game
  .gitignore
  Makefile
  README.md
  include/graphics/menu.h
  include/logic/bullet.h
  include/logic/enemy.h
  include/logic/game.h
  include/logic/models.h
  include/logic/user.h
  include/network/client.h
  include/network/server.h
  src/client.c
  src/graphics/menu.c
  src/logic/bullet.c
  src/logic/enemy.c
  src/logic/game.c
  src/logic/models.c
  src/logic/user.c
  src/main_client.c
  src/main_server.c
  src/network/client.c
  src/network/server.c
Labels: Bug

#11 fix and new funcs
  include/graphics/menu.h
  include/logic/enemy.h
  include/logic/game.h
  include/logic/user.h
  src/graphics/menu.c
  src/logic/enemy.c
  src/logic/game.c
  src/logic/user.c
  src/main_client.c
Labels: Merge

#12 Fix
  include/graphics/menu.h
  include/logic/enemy.h
  include/logic/game.h
  include/logic/user.h
  include/network/client.h
  src/graphics/menu.c
  src/logic/enemy.c
  src/logic/game.c
  src/logic/user.c
  src/main_client.c
  src/network/client.c
Labels: Merge

#13 Graphics
  include/graphics/menu.h
  src/graphics/menu.c
  src/main_client.c
Labels: Merge

#14 Reload coord
  include/logic/user.h
  src/graphics/menu.c
  src/logic/bullet.c
  src/logic/user.c
  src/main_client.c
Labels: Merge

#17 Network 1
  include/network/client.h
  include/network/server.h
  src/network/client.c
  src/network/server.c
Labels: Review

#16 Network stuthedian
  include/graphics/menu.h
  include/network/client.h
  include/network/server.h
  src/graphics/menu.c
  src/main_client.c
  src/main_server.c
  src/network/client.c
  src/network/server.c
Labels: Merge

#19 Send info
  include/config.h
  include/graphics/menu.h
  include/logic/user.h
  include/network/client.h
  include/network/server.h
  src/graphics/menu.c
  src/logic/user.c
  src/main_client.c
  src/network/client.c
  src/network/server.c
Labels: Fix, Merge, Review

#20 added bullet list
  include/logic/bullet.h
  include/logic/bullet_list.h
  include/logic/user.h
  src/graphics/menu.c
  src/logic/bullet.c
  src/logic/bullet_list.c
  src/logic/user.c
Labels: Review

#21 Redraw second player when first player is moving
  include/logic/game.h
  include/network/client.h
  src/graphics/menu.c
  src/logic/game.c
  src/logic/user.c
  src/main_client.c
  src/network/client.c
  src/network/server.c
Labels: Review

#23 Network 1
  include/config.h
  include/logic/bullet_list.h
  include/logic/user.h
  include/network/server.h
  src/graphics/menu.c
  src/logic/bullet_list.c
  src/logic/user.c
  src/network/client.c
  src/network/server.c
Labels: Review
